# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Delivery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Delivery
	 
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'

#    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

#    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
#
#    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
#
#    pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'

    # pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  end
